DROP TABLE IF EXISTS countries;

CREATE TABLE public.countries (
    c_id SERIAL PRIMARY KEY NOT NULL,
    c_name VARCHAR(255) NOT NULL,
    c_code VARCHAR(3) NOT NULL
);

INSERT INTO countries(c_id, c_name, c_code) VALUES
(0, 'United States of America', 'USA'),
(1, 'Afghanistan', 'AFG'),
(2, 'Albania', 'ALB'),
(3, 'Algeria', 'DZA'),
(4, 'Andorra', 'AND'),
(5, 'Angola', 'AGO'),
(6, 'Antigua & Deps', 'ATG'),
(7, 'Argentina', 'ARG'),
(8, 'Armenia', 'ARM'),
(9, 'Australia', 'AUS'),
(10, 'Austria', 'AUT'),
(11, 'Azerbaijan', 'AZE'),
(12, 'Bahamas', 'BHS'),
(13, 'Bahrain', 'BHR'),
(14, 'Bangladesh', 'BGD'),
(15, 'Barbados', 'BRB'),
(16, 'Belarus', 'BLR'),
(17, 'Belgium', 'BEL'),
(18, 'Belize', 'BLZ'),
(19, 'Benin', 'BEN'),
(20, 'Bhutan', 'BTN'),
(21, 'Bolivia', 'BOL'),
(22, 'Bosnia Herzegovina', 'BIH'),
(23, 'Botswana', 'BWA'),
(24, 'Brazil', 'BRA'),
(25, 'Brunei', 'BRN'),
(26, 'Bulgaria', 'BGR'),
(27, 'Burkina', 'BFA'),
(28, 'Burma', 'MMR'),
(29, 'Burundi', 'BDI'),
(30, 'Cambodia', 'KHM'),
(31, 'Cameroon', 'CMR'),
(32, 'Canada', 'CAN'),
(33, 'Cape Verde', 'CPV'),
(34, 'Central African Rep', 'CAF'),
(35, 'Chad', 'TCD'),
(36, 'Chile', 'CHL'),
(37, 'China', 'CHN'),
(38, 'Colombia', 'COL'),
(39, 'Comoros', 'COM'),
(40, 'Democratic Republic of the Congo', 'COD'),
(41, 'Republic of the Congo', 'COG'),
(42, 'Costa Rica', 'CRI'),
(43, 'Croatia', 'HRV'),
(44, 'Cuba', 'CUB'),
(45, 'Cyprus', 'CYP'),
(46, 'Czech Republic', 'CZE'),
(47, 'Denmark', 'DNK'),
(48, 'Djibouti', 'DJI'),
(49, 'Dominica', 'DMA'),
(50, 'Dominican Republic', 'DOM'),
(51, 'East Timor', 'TLS'),
(52, 'Ecuador', 'ECU'),
(53, 'Egypt', 'EGY'),
(54, 'El Salvador', 'SLV'),
(55, 'Equatorial Guinea', 'GNQ'),
(56, 'Eritrea', 'ERI'),
(57, 'Estonia', 'EST'),
(58, 'Ethiopia', 'ETH'),
(59, 'Fiji', 'FJI'),
(60, 'Finland', 'FIN'),
(61, 'France', 'FRA'),
(62, 'Gabon', 'GAB'),
(63, 'The Gambia', 'GMB'),
(64, 'Georgia', 'GEO'),
(65, 'Germany', 'DEU'),
(66, 'Ghana', 'GHA'),
(67, 'Greece', 'GRC'),
(68, 'Grenada', 'GRD'),
(69, 'Guatemala', 'GTM'),
(70, 'Guinea', 'GIN'),
(71, 'Guinea-Bissau', 'GNB'),
(72, 'Guyana', 'GUY'),
(73, 'Haiti', 'HTI'),
(74, 'Honduras', 'HND'),
(75, 'Hungary', 'HUN'),
(76, 'Iceland', 'ISL'),
(77, 'India', 'IND'),
(78, 'Indonesia', 'IDN'),
(79, 'Iran', 'IRN'),
(80, 'Iraq', 'IRQ'),
(81, 'Republic of Ireland', 'IRL'),
(82, 'Israel', 'ISR'),
(83, 'Italy', 'ITA'),
(84, 'Ivory Coast', 'CIV'),
(85, 'Jamaica', 'JAM'),
(86, 'Japan', 'JPN'),
(87, 'Jordan', 'JOR'),
(88, 'Kazakhstan', 'KAZ'),
(89, 'Kenya', 'KEN'),
(90, 'Kiribati', 'KIR'),
(91, 'North Korea', 'PRK'),
(92, 'South Korea', 'KOR'),
(93, 'Kosovo', 'XKX'),
(94, 'Kuwait', 'KWT'),
(95, 'Kyrgyzstan', 'KGZ'),
(96, 'Laos', 'LAO'),
(97, 'Latvia', 'LVA'),
(98, 'Lebanon', 'LBN'),
(99, 'Lesotho', 'LSO'),
(100, 'Liberia', 'LBR'),
(101, 'Libya', 'LBY'),
(102, 'Liechtenstein', 'LIE'),
(103, 'Lithuania', 'LTU'),
(104, 'Luxembourg', 'LUX'),
(105, 'Macedonia', 'MKD'),
(106, 'Madagascar', 'MDG'),
(107, 'Malawi', 'MWI'),
(108, 'Malaysia', 'MYS'),
(109, 'Maldives', 'MDV'),
(110, 'Mali', 'MLI'),
(111, 'Malta', 'MLT'),
(112, 'Marshall Islands', 'MHL'),
(113, 'Mauritania', 'MRT'),
(114, 'Mauritius', 'MUS'),
(115, 'Mexico', 'MEX'),
(116, 'Micronesia', 'FSM'),
(117, 'Moldova', 'MDA'),
(118, 'Monaco', 'MCO'),
(119, 'Mongolia', 'MNG'),
(120, 'Montenegro', 'MNE'),
(121, 'Morocco', 'MAR'),
(122, 'Mozambique', 'MOZ'),
(123, 'Namibia', 'NAM'),
(124, 'Nauru', 'NRU'),
(125, 'Nepal', 'NPL'),
(126, 'Netherlands', 'NLD'),
(127, 'New Zealand', 'NZL'),
(128, 'Nicaragua', 'NIC'),
(129, 'Niger', 'NER'),
(130, 'Nigeria', 'NGA'),
(131, 'Norway', 'NOR'),
(132, 'Oman', 'OMN'),
(133, 'Pakistan', 'PAK'),
(134, 'Palau', 'PLW'),
(135, 'Panama', 'PAN'),
(136, 'Papua New Guinea', 'PNG'),
(137, 'Paraguay', 'PRY'),
(138, 'Peru', 'PER'),
(139, 'Philippines', 'PHL'),
(140, 'Poland', 'POL'),
(141, 'Portugal', 'PRT'),
(142, 'Qatar', 'QAT'),
(143, 'Romania', 'ROU'),
(144, 'Russian Federation', 'RUS'),
(145, 'Rwanda', 'RWA'),
(146, 'Samoa', 'WSM'),
(147, 'San Marino', 'SMR'),
(148, 'Sao Tome & Principe', 'STP'),
(149, 'Saudi Arabia', 'SAU'),
(150, 'Senegal', 'SEN'),
(151, 'Serbia', 'SRB'),
(152, 'Seychelles', 'SYC'),
(153, 'Sierra Leone', 'SLE'),
(154, 'Singapore', 'SGP'),
(155, 'Slovakia', 'SVK'),
(156, 'Slovenia', 'SVN'),
(157, 'Solomon Islands', 'SLB'),
(158, 'Somalia', 'SOM'),
(159, 'South Africa', 'ZAF'),
(160, 'Spain', 'ESP'),
(161, 'Sri Lanka', 'LKA'),
(162, 'Sudan', 'SDN'),
(163, 'Suriname', 'SUR'),
(164, 'Swaziland', 'SWZ'),
(165, 'Sweden', 'SWE'),
(166, 'Switzerland', 'CHE'),
(167, 'Syria', 'SYR'),
(168, 'Tajikistan', 'TJK'),
(169, 'Tanzania', 'TZA'),
(170, 'Thailand', 'THA'),
(171, 'Togo', 'TGO'),
(172, 'Tonga', 'TON'),
(173, 'Trinidad & Tobago', 'TTO'),
(174, 'Tunisia', 'TUN'),
(175, 'Turkey', 'TUR'),
(176, 'Turkmenistan', 'TKM'),
(177, 'Tuvalu', 'TUV'),
(178, 'Uganda', 'UGA'),
(179, 'Ukraine', 'UKR'),
(180, 'United Arab Emirates', 'ARE'),
(181, 'United Kingdom', 'GBR'),
(182, 'Uruguay', 'URY'),
(183, 'Uzbekistan', 'UZB'),
(184, 'Vanuatu', 'VUT'),
(185, 'Vatican City', 'VAT'),
(186, 'Venezuela', 'VEN'),
(187, 'Vietnam', 'VNM'),
(188, 'Yemen', 'YEM'),
(189, 'Zambia', 'ZMB'),
(190, 'Zimbabwe', 'ZWE');

SELECT setval(pg_get_serial_sequence('countries', 'c_id'), (SELECT MAX(c_id) FROM countries));